### ISSUE TITLE
Doesn't seem to work on latest Chrome

### ISSUE THREAD

**Issue by illtellyoulater** [wo80/bookmarks#1]
Nothing is shown, except an empty side bar on the left, and the search bar on top.

**Comment by wo80** [comment]
Should be fixed with latest commit.

**Comment by mark-c** [comment]
Sorry, how do I use this? Do I need to download the file?

Ok, so disabling uBlockO and going to this page gives the same thing. When I drop (it says +Copy) the **.json** file it just reads it in a new tab. Ah, looks it's a Session buddy .json file from 2021.

https://htmlpreview.github.io/?https://github.com/wo80/bookmarks/blob/master/index.html


Using Chrome Version 109.0.5414.120 (Official Build) (64-bit)

**Comment by wo80** [comment]
@mark-c I tested with latest Vivaldi and it works as expected.

1) Don't use htmlpreview.github.io, use the demo site or host the app yourself.
2) The Chromuim bookmarks file is just named `Bookmarks`. You have to rename it to `Bookmarks.json` (adding the file extension) to get loaded correctly (EDIT: obviously, you want to do this with a copy of that file, so Chrome can still find the original file).
